name: CI - Build minishell

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    name: Build with make
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run:  |
          sudo apt-get update
          sudo apt-get install -y build-essential libreadline-de

      - name: Clean previous builds
        run: make fclean || true

      - name: Compile project
        run: make

      - name: Check output binary
        run:  |
          if [ ! -f minishell ]; then
            echo "‚ùå Error: No se ha generado el ejecutable minishell"
            exit 1
          fi